name: ty

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ty:
    name: ty
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      # https://github.com/astral-sh/setup-uv
      - name: Set up uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Run ty
        run: uvx ty check .
